language: node_js

os:
  - linux
  - osx

dist: xenial

node_js:
  - node

services:
  - xvfb

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test
