language: node_js

os:
  - linux
  - osx

dist: xenial

addons:
  apt:
    packages:
      - libxss1

node_js:
  - node

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get install libxss1 ; fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test
