name: CD
on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install vsce
        run: npm install -g vsce
      - name: Install dependencies
        run: yarn install
      - name: Publish
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
